/**
 * AI triage constants and utility functions for Phase 3 (AI Power).
 */

// ============================================
// Confidence Thresholds
// ============================================

export const CONFIDENCE_HIGH = 0.8;
export const CONFIDENCE_MEDIUM = 0.5;

// ============================================
// Batch Limits
// ============================================

export const DEFAULT_BATCH_SIZE = 50;
export const DEFAULT_CONFIRM_ABOVE = 10;
export const MAX_SPLIT_SUB_ISSUES = 5;
export const APPLY_INTER_ITEM_DELAY = 100;

// ============================================
// Threshold Bounds
// ============================================

export const THRESHOLD_MIN = 0.5;
export const THRESHOLD_MAX = 1.0;
export const THRESHOLD_STEP = 0.05;

// ============================================
// Trust Levels
// ============================================

export type TrustLevel = 'crawl' | 'walk' | 'run';

export const TRUST_LEVEL_LABELS: Record<TrustLevel, string> = {
  crawl: 'Suggestions Only',
  walk: 'Auto-Apply Above Threshold',
  run: 'Fully Automated',
};

// ============================================
// Enrichment Comment
// ============================================

export const ENRICHMENT_COMMENT_FOOTER = '---\n*Generated by Auto-Claude AI Triage*';

// ============================================
// Utility Functions
// ============================================

export function getConfidenceLevel(confidence: number): 'high' | 'medium' | 'low' {
  if (confidence >= CONFIDENCE_HIGH) return 'high';
  if (confidence >= CONFIDENCE_MEDIUM) return 'medium';
  return 'low';
}

export function isValidThreshold(value: number): boolean {
  if (Number.isNaN(value)) return false;
  return value >= THRESHOLD_MIN && value <= THRESHOLD_MAX;
}

export function clampThreshold(value: number): number {
  return Math.max(THRESHOLD_MIN, Math.min(THRESHOLD_MAX, value));
}

/**
 * Estimates the cost of a batch triage operation.
 * Uses rough per-issue token cost estimates.
 */
export function estimateBatchCost(issueCount: number, model: string): string {
  const costPerIssue = model.includes('haiku') ? 0.0008 : 0.0035;
  return `~$${(issueCount * costPerIssue).toFixed(2)}`;
}

/**
 * Formats an AIEnrichmentResult into a markdown comment for GitHub.
 */
export function formatEnrichmentComment(result: {
  problem: string;
  goal: string;
  acceptanceCriteria: string[];
  risksEdgeCases: string[];
}): string {
  const lines: string[] = ['## AI Enrichment Summary', ''];
  lines.push(`**Problem:** ${result.problem}`, '');
  lines.push(`**Goal:** ${result.goal}`, '');
  if (result.acceptanceCriteria.length > 0) {
    lines.push('### Acceptance Criteria');
    for (const ac of result.acceptanceCriteria) {
      lines.push(`- ${ac}`);
    }
    lines.push('');
  }
  if (result.risksEdgeCases.length > 0) {
    lines.push('### Risks & Edge Cases');
    for (const risk of result.risksEdgeCases) {
      lines.push(`- ${risk}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
